### ISSUE TITLE
The log file /tmp/aimlbotkernel.log causes error in Jupyterhub

### ISSUE THREAD

**Issue by cloudgen** [paulovn/aiml-chatbot-kernel#14]
In a multi-user environment such as Jupyterhub, the first user created a log file in /tmp/aimlbotkernel.log under the privilege of that user.  

When there is another user trying to connect to the kernel, the user cannot open the /tmp/aimlbotkernel.log which causes crashes.

**Comment by paulovn** [comment]
Right you are. This was not thought for a multi-user environment. The problem is that the standard Python logger does not care for the logfile permissions, so I guess it depends on the user's umask.

As a quick hack, I've changed the code to add the userid as part of the logfilename, i.e. `aimlbotkernel-<uid>.log`. That should avoid collisions (and put the logs of different users in a different files, which is probably a bonus). 

Should have been solved by https://github.com/paulovn/aiml-chatbot-kernel/pull/15
